name: 07- using expression

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up'
        if: ${{ inputs.debug }}
        run: |
          echo "Trigerred by: ${{ github.event_name }}
          echo: "Runner os: ${{ runner.os }}
      - name: '[debug] Print when triggered from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo"I was trigered from main"
      - name: Greeting
        run:
          echo "Hello world"
      
